steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      # - '-t'
      # - '$_IMAGE_NAME:$SHORT_SHA'
      - '-t'
      - '$_IMAGE_NAME'
      # - '-t'
      # - '$_IMAGE_NAME:master'
      - '../'
      - '-f'
      - $_DOCKERFILE_NAME
    dir: $_DOCKERFILE_DIR
    id: Build

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_IMAGE_NAME'
    id: Push
  - name: gcr.io/cloud-builders/gke-deploy
    args:
      - prepare
      - '--filename=$_K8S_YAML_PATH'
      - '--image=$_IMAGE_NAME:$SHORT_SHA'
      - '--app=$_K8S_APP_NAME'
      - '--version=$COMMIT_SHA'
      - '--namespace=$_K8S_NAMESPACE'
      - '--label=$_K8S_LABELS'
      - '--annotation=$_K8S_ANNOTATIONS,gcb-build-id=$BUILD_ID'
      - '--create-application-cr'
      - >-
        --links="Build
        details=https://console.cloud.google.com/cloud-build/builds/$BUILD_ID?project=$PROJECT_ID"
      - '--output=output'

    id: Prepare deploy
  # - name: gcr.io/cloud-builders/gsutil
  #   args:
  #     - '-c'
  #     - |-
  #       then
  #         gsutil cp -r output/suggested gs://$_OUTPUT_BUCKET_PATH/config/$_K8S_APP_NAME/$BUILD_ID/suggested
  #         gsutil cp -r output/expanded gs://$_OUTPUT_BUCKET_PATH/config/$_K8S_APP_NAME/$BUILD_ID/expanded
  #       fi
  #   id: Save configs
    entrypoint: sh
  - name: gcr.io/cloud-builders/gke-deploy
    args:
      - apply
      # - '--filename=output/expanded'
      - '--cluster=$_GKE_CLUSTER'
      - '--location=$_GKE_LOCATION'
      - '--namespace=$_K8S_NAMESPACE'
    id: Apply deploy
images:
  # - '$_IMAGE_NAME:$SHORT_SHA'
  - '$_IMAGE_NAME'
options:
  substitutionOption: ALLOW_LOOSE
tags:
  - gcp-cloud-build-deploy
  - $_K8S_APP_NAME
timeout: 1000s