steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - '$_IMAGE_NAME:$SHORT_SHA'
      - '-t'
      - '$_IMAGE_NAME'
      - '-t'
      - '$_IMAGE_NAME:master'
      - '../'
      - '-f'
      - $_DOCKERFILE_NAME
    dir: $_DOCKERFILE_DIR
    id: Build

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_IMAGE_NAME'
      
timeout: 1000s